# PostgreSQL Database Connection
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "YOUR_OAUTH2_ISSUER_URI"

cors:
  allowed-origins: http://localhost:3000

springdoc:
  version: '@project.version@'

security:
  white-list-urls:
    - "/public/**"
    - "/v3/api-docs/**"
    - "/swagger-ui/**"
    - "/swagger-ui.html"
