# PostgreSQL Database Connection
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    username: postgres
    password: postgres

  # JPA and Hibernate Configuration
  # Use 'validate' to ensure the schema created by Flyway matches the entities.
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
